In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import scipy.io
import numpy as np
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split


In [3]:
input_data=scipy.io.loadmat('/content/drive/MyDrive/NNFL data/Data_A2/input.mat')
class_label_data=scipy.io.loadmat('/content/drive/MyDrive/NNFL data/Data_A2/class_label.mat')

In [6]:
input_data=pd.DataFrame(input_data["x"]) 
#cols = input_data.select_dtypes(exclude=['float']).columns
#input_data[cols] = input_data[cols].apply(pd.to_numeric, downcast='float', errors='coerce')
input_data=(np.asarray(input_data)).T 
print(input_data.dtype)
class_label_data=np.asarray(class_label_data["y"])

object


In [7]:
data_input=[]
for i in range(len(input_data)):
    data_input.append(input_data[i][0])
data_input=np.asarray(data_input)
print(data_input)
#data_input=np.reshape(data_input, (data_input.shape[0], 1)) 
print(data_input.shape)
data_input=data_input.transpose(0,2,1)
for i in range(len(data_input)):
    data_input[i]=preprocessing.normalize(data_input[i])

[[[-0.02942547 -0.03004717 -0.03063448 ... -0.00171387 -0.00150202
   -0.00129178]
  [-0.03354165 -0.0335658  -0.03354647 ... -0.00397835 -0.00348932
   -0.00299711]
  [-0.0041002  -0.00350403 -0.00289871 ... -0.0023221  -0.00203756
   -0.00174853]
  ...
  [-0.01438948 -0.01302857 -0.01166126 ...  0.00079799  0.00065684
    0.0005333 ]
  [-0.02843199 -0.0272833  -0.02612498 ...  0.00120509  0.00103033
    0.0008662 ]
  [-0.00433259 -0.00382339 -0.00330092 ... -0.00397676 -0.00337576
   -0.00281225]]

 [[-0.02942547 -0.03004717 -0.03063448 ... -0.00171387 -0.00150202
   -0.00129178]
  [-0.03354165 -0.0335658  -0.03354647 ... -0.00397835 -0.00348932
   -0.00299711]
  [-0.0041002  -0.00350403 -0.00289871 ... -0.0023221  -0.00203756
   -0.00174853]
  ...
  [-0.01438948 -0.01302857 -0.01166126 ...  0.00079799  0.00065684
    0.0005333 ]
  [-0.02843199 -0.0272833  -0.02612498 ...  0.00120509  0.00103033
    0.0008662 ]
  [-0.03536238 -0.03581917 -0.03625893 ... -0.00944339 -0.00816656
   -0.

In [8]:
data_input=data_input.astype(np.float)
print(data_input)
print(data_input.dtype)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


[[[-0.40125279 -0.45738194 -0.05591131 ... -0.19621842 -0.38770543
   -0.05908019]
  [-0.41160141 -0.45980145 -0.04800002 ... -0.17847202 -0.37374054
   -0.0523747 ]
  [-0.42141005 -0.46146759 -0.03987491 ... -0.16041305 -0.35937711
   -0.0454077 ]
  ...
  [-0.19797961 -0.45956381 -0.26823974 ...  0.09218033  0.13920735
   -0.45938054]
  [-0.20131779 -0.46767903 -0.27309765 ...  0.08803666  0.13809689
   -0.45245752]
  [-0.20465272 -0.4748241  -0.27701496 ...  0.08449011  0.13722921
   -0.44553836]]

 [[-0.36193933 -0.41256913 -0.0504333  ... -0.17699357 -0.3497193
   -0.43496452]
  [-0.36992545 -0.41324509 -0.04313987 ... -0.16040116 -0.33589812
   -0.44098743]
  [-0.37741609 -0.41329174 -0.03571209 ... -0.1436664  -0.32185921
   -0.44670924]
  ...
  [-0.14073517 -0.3266841  -0.19068007 ...  0.06552702  0.0989565
   -0.77544818]
  [-0.14258944 -0.33124788 -0.19342971 ...  0.06235464  0.09781132
   -0.77526631]
  [-0.14462615 -0.33555373 -0.19576387 ...  0.05970837  0.0969786
   -0.774

In [9]:
data_class=[]
for i in range(len(class_label_data)):
    data_class.append(class_label_data[i][0]-1)
data_class=np.asarray(data_class)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(data_input, data_class, test_size=0.2, random_state=5)
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.125, random_state=5)

In [11]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Conv1D(input_shape=(800,12),filters=20,kernel_size=7,padding="same",activation="relu"))
model.add(tf.keras.layers.Conv1D(filters=20,kernel_size=7,padding="same",activation="relu"))
model.add(tf.keras.layers.MaxPool1D(pool_size=3,strides=3))
model.add(tf.keras.layers.Conv1D(filters=60,kernel_size=7,padding="same",activation="relu"))
model.add(tf.keras.layers.Conv1D(filters=60,kernel_size=7,padding="same",activation="relu"))
model.add(tf.keras.layers.MaxPool1D(pool_size=3,strides=3))
model.add(tf.keras.layers.Dropout(0.7))
model.add(tf.keras.layers.Conv1D(filters=120,kernel_size=7,padding="same",activation="relu"))
model.add(tf.keras.layers.Conv1D(filters=120,kernel_size=7,padding="same",activation="relu")) 
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(units=2000,activation="relu")) 
model.add(tf.keras.layers.Dense(units=700,activation="relu")) 
model.add(tf.keras.layers.Dense(units=50,activation="relu")) 
model.add(tf.keras.layers.Dense(units=7,activation="sigmoid")) 







In [12]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 800, 20)           1700      
                                                                 
 conv1d_1 (Conv1D)           (None, 800, 20)           2820      
                                                                 
 max_pooling1d (MaxPooling1D  (None, 266, 20)          0         
 )                                                               
                                                                 
 conv1d_2 (Conv1D)           (None, 266, 60)           8460      
                                                                 
 conv1d_3 (Conv1D)           (None, 266, 60)           25260     
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 88, 60)           0         
 1D)                                                    

In [13]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt,loss=tf.keras.losses.SparseCategoricalCrossentropy(),metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, epochs=2, batch_size=200, validation_data=(X_valid,y_valid))

Epoch 1/2
61/61 [==============================] - 112s 2s/step - loss: 0.0047 - accuracy: 0.9988 - val_loss: 0.0039 - val_accuracy: 0.9988
Epoch 2/2
61/61 [==============================] - 109s 2s/step - loss: 0.0034 - accuracy: 0.9993 - val_loss: 2.1172e-04 - val_accuracy: 1.0000


In [16]:
model.evaluate(X_test,y_test)

108/108 [==============================] - 10s 90ms/step - loss: 0.0016 - accuracy: 0.9994


[0.0015695691108703613, 0.999417245388031]

In [17]:
y_pred=np.argmax(model.predict(X_test), axis=-1)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
confusion_m=confusion_matrix(y_test,y_pred)
for i in range(7):
    print("Accuracy for class {0}: {1}%".format(i+1,(confusion_m.diagonal()/confusion_m.sum(axis=1))[i] *100))

print("\n")
print(confusion_m)

Accuracy for class 1: 100.0%
Accuracy for class 2: 99.49367088607595%
Accuracy for class 3: 97.12230215827337%
Accuracy for class 4: 98.48484848484848%
Accuracy for class 5: 87.44038155802862%
Accuracy for class 6: 85.34201954397395%
Accuracy for class 7: 100.0%


[[567   0   0   0   0   0   0]
 [  2 393   0   0   0   0   0]
 [ 16   0 540   0   0   0   0]
 [  5   0   0 325   0   0   0]
 [ 79   0   0   0 550   0   0]
 [ 26   0  19   0  45 524   0]
 [  0   0   0   0   0   0 341]]


In [20]:
print("Number of correctly predicted class labels are: {0}".format(np.sum(y_pred==y_test)))
print("Total number of class labels are: {0}".format(len(y_test)))
print("Overall Accuracy is: {0}%".format(np.sum(y_pred==y_test)/len(y_test)*100))

Number of correctly predicted class labels are: 3240
Total number of class labels are: 3432
Overall Accuracy is: 94.4055944055944%
