Q4 ONE VS ALL

MOUNTING THE DRIVE

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


importing libraries

In [2]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import sklearn
np.random.seed(0)

In [3]:
from sklearn.model_selection import train_test_split

DEFINING SIGMOID FUNCTION

In [4]:
def sigmoid(x):
  x = x.astype(float)
  z = np.exp(-x)
  sig = 1 / (1 + z)
  return sig


DEFINING SET FUNCTION

In [5]:
def set(y):
    for i in range(len(y)):
        if(y[i]>=0.5):
            y[i] = 1
        if(y[i]<0.5):
            y[i] = 0
    return y


DEFINING GRADIENT DESCENT FUNCTIONS

In [6]:

def batch_gradient_descent(X,y,w,alpha,iters):
  
  cost_history = np.zeros(iters) # cost function for each iteration
  
  #initalize our cost history list to store the cost function on every iteration
  
  for i in range(iters):
    z = np.dot(X,w.T)
    hypothesis = sigmoid(z)
    w = w -  alpha * np.dot((hypothesis-y), X) #weight updation
  
  return w

In [7]:
def batch_gradient_descent_l1(X,y,w,alpha,iters,lamb):
  
  cost_history = np.zeros(iters) # cost function for each iteration
  
  #initalize our cost history list to store the cost function on every iteration
  
  for i in range(iters):
    z = np.dot(X,w.T)
    hypothesis = sigmoid(z)
    w = w -  alpha * np.dot((hypothesis-y), X) - ((alpha*lamb/2)*np.sign(w))#weight updation
  
  return w

In [8]:
def batch_gradient_descent_l2(X,y,w,alpha,iters,lamb):
  
  cost_history = np.zeros(iters) # cost function for each iteration
  
  #initalize our cost history list to store the cost function on every iteration
  
  for i in range(iters):
    z = np.dot(X,w.T)
    hypothesis = sigmoid(z)
    w = w*(1-alpha*lamb) -  alpha * np.dot((hypothesis-y), X) #weight updation
  
  return w

LOADING THE DATA

In [9]:
data = pd.read_excel('/content/drive/MyDrive/nnfl data/data.xlsx',header=None)

In [10]:
datan=data.values
X=datan[:,0:datan.shape[1]-1]
y=datan[:,datan.shape[1]-1]
print(data.shape)


(3412, 61)


SPLITTING THE DATA INTO TRAINING, VALIDATION AND TESTING using holdout validation

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, shuffle = True, random_state = 8)
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train,test_size=0.125, shuffle = True, random_state = 8)


NOMRALISING TESTING AND TRAINING DATA, ADDING BIAS VECTOR

In [12]:
m=X_train.shape[0] 
n=X_test.shape[0]

qq = np.ones([n, 1])

xmin1 = np.min(X_test, axis = 0) 
xmax1 = np.max(X_test, axis = 0) 

X_test = (X_test- xmin1)/(xmax1-xmin1)

X_test = np.append(qq,X_test, axis=1)
print(X_test.shape)

(683, 61)


In [13]:
xmin = np.min(X_train, axis = 0) 
xmax = np.max(X_train, axis = 0) 

X_train = (X_train- xmin)/(xmax-xmin)
print(X_train)

[[0.39328586 0.16654807 0.16214643 ... 0.23299547 0.81403191 0.93200908]
 [0.11627088 0.11346816 0.21845213 ... 0.15076686 0.67705128 0.63106166]
 [0.51419012 0.52397105 0.22901312 ... 0.46541911 0.83192827 0.79023879]
 ...
 [0.63425256 0.53253442 0.3768769  ... 0.64252927 0.71068596 0.75504019]
 [0.29051515 0.30674267 0.25506676 ... 0.3681679  0.877832   0.63315738]
 [0.56033294 0.29998019 0.37576393 ... 0.3886692  0.76985938 0.700262  ]]


In [14]:
pp = np.ones([m, 1])
X_train = np.append(pp,X_train, axis=1) #Column of ones 

print(X_train)

[[1.         0.39328586 0.16654807 ... 0.23299547 0.81403191 0.93200908]
 [1.         0.11627088 0.11346816 ... 0.15076686 0.67705128 0.63106166]
 [1.         0.51419012 0.52397105 ... 0.46541911 0.83192827 0.79023879]
 ...
 [1.         0.63425256 0.53253442 ... 0.64252927 0.71068596 0.75504019]
 [1.         0.29051515 0.30674267 ... 0.3681679  0.877832   0.63315738]
 [1.         0.56033294 0.29998019 ... 0.3886692  0.76985938 0.700262  ]]


MAKING TRAINING MODELS FOR OVE VS ALL 4 CASES

In [15]:
y1_tr = [1 for i in range(len(y_train))]
y2_tr = [1 for i in range(len(y_train))]
y3_tr = [1 for i in range(len(y_train))]
y4_tr = [1 for i in range(len(y_train))]
for i in range(len(y_train)):
    if(y_train[i] != 1):
        y1_tr[i] = 0
    if(y_train[i] != 2):
        y2_tr[i] = 0
    if(y_train[i] != 3):
        y3_tr[i] = 0
    if(y_train[i] != 4):
        y4_tr[i] = 0
print(y4_tr)

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 

IMPLEMETING ONE VS ALL FOR BATCH GRADIENT DESCENT MULTICLASS LOR

In [16]:
alpha=0.0025
iters=1000

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m1 = batch_gradient_descent(X_train,y1_tr,w,alpha,iters)
y_p1 = np.dot(X_test,w_m1.T)
y_p1 = set(y_p1)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m2 = batch_gradient_descent(X_train,y2_tr,w,alpha,iters)
y_p2 = np.dot(X_test,w_m2.T)
y_p2 = set(y_p2)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m3 = batch_gradient_descent(X_train,y3_tr,w,alpha,iters)
y_p3 = np.dot(X_test,w_m3.T)
y_p3 = set(y_p3)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m4 = batch_gradient_descent(X_train,y4_tr,w,alpha,iters)
y_p4 = np.dot(X_test,w_m4.T)
y_p4 = set(y_p4)




In [17]:
cval = [0 for i in range(len(y_test))]
for i in range(len(y_test)):
    if (y_p1[i] == 1):
        cval[i] = 1.0
    if (y_p2[i] == 1):
        cval[i] = 2.0
    if (y_p3[i] == 1):
        cval[i] = 3.0
    if (y_p4[i] == 1):
        cval[i] = 4.0


GENERATING THE CONFUSION MATRIX

In [18]:

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, cval)

print(cm)

[[  8   2 143   8]
 [  6   0 136  25]
 [  6   0 158  15]
 [  9   3 149  15]]


FINDING INDIVIDUAL CLASS ACCURACY AND OVERALL ACCURACY 

In [19]:
confmat = np.asarray(cm)
Acc = (confmat[0][0] + confmat[1][1] + confmat[2][2])/sum(sum(confmat))
Acc1 = confmat[0][0]/sum(confmat[0])
Acc2 = confmat[1][1]/sum(confmat[1])
Acc3 = confmat[2][2]/sum(confmat[2])
Acc4 = confmat[3][3]/sum(confmat[3])
print('Overall Accuracy : ' + str(Acc))
print('Accuracy of class 1 : ' + str(Acc1))
print('Accuracy of class 2 : ' + str(Acc2))
print('Accuracy of class 3 : ' + str(Acc3))
print('Accuracy of class 4 : ' + str(Acc4))

Overall Accuracy : 0.2430453879941435
Accuracy of class 1 : 0.049689440993788817
Accuracy of class 2 : 0.0
Accuracy of class 3 : 0.88268156424581
Accuracy of class 4 : 0.08522727272727272


IMPLEMETING ONE VS ALL FOR BATCH GRADIENT DESCENT MULTICLASS LOR WITH L1

In [20]:
alpha=0.0025
iters=1000
lamb=1
w= np.zeros((X_train.shape[1])) ###weight initialization
w_m1 = batch_gradient_descent_l1(X_train,y1_tr,w,alpha,iters,lamb)
y_p1 = np.dot(X_test,w_m1.T)
y_p1 = set(y_p1)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m2 = batch_gradient_descent_l1(X_train,y2_tr,w,alpha,iters,lamb)
y_p2 = np.dot(X_test,w_m2.T)
y_p2 = set(y_p2)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m3 = batch_gradient_descent_l1(X_train,y3_tr,w,alpha,iters,lamb)
y_p3 = np.dot(X_test,w_m3.T)
y_p3 = set(y_p3)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m4 = batch_gradient_descent_l1(X_train,y4_tr,w,alpha,iters,lamb)
y_p4 = np.dot(X_test,w_m4.T)
y_p4 = set(y_p4)



In [21]:
cval = [0 for i in range(len(y_test))]
for i in range(len(y_test)):
    if (y_p1[i] == 1):
        cval[i] = 1.0
    if (y_p2[i] == 1):
        cval[i] = 2.0
    if (y_p3[i] == 1):
        cval[i] = 3.0
    if (y_p4[i] == 1):
        cval[i] = 4.0

GENERATING THE CONFUSION MATRIX

In [22]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, cval)

print(cm)

[[  9   2 144   6]
 [  6   0 137  24]
 [  6   1 157  15]
 [  8   3 153  12]]


FINDING INDIVIDUAL CLASS ACCURACY AND OVERALL ACCURACY

In [23]:
confmat = np.asarray(cm)
Acc = (confmat[0][0] + confmat[1][1] + confmat[2][2])/sum(sum(confmat))
Acc1 = confmat[0][0]/sum(confmat[0])
Acc2 = confmat[1][1]/sum(confmat[1])
Acc3 = confmat[2][2]/sum(confmat[2])
Acc4 = confmat[3][3]/sum(confmat[3])
print('Overall Accuracy : ' + str(Acc))
print('Accuracy of class 1 : ' + str(Acc1))
print('Accuracy of class 2 : ' + str(Acc2))
print('Accuracy of class 3 : ' + str(Acc3))
print('Accuracy of class 4 : ' + str(Acc4))

Overall Accuracy : 0.2430453879941435
Accuracy of class 1 : 0.055900621118012424
Accuracy of class 2 : 0.0
Accuracy of class 3 : 0.8770949720670391
Accuracy of class 4 : 0.06818181818181818


IMPLEMETING ONE VS ALL FOR BATCH GRADIENT DESCENT MULTICLASS LOR WITH L1

In [24]:
alpha=0.0025
iters=1000
lamb=1

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m1 = batch_gradient_descent_l2(X_train,y1_tr,w,alpha,iters,lamb)
y_p1 = np.dot(X_test,w_m1.T)
y_p1 = set(y_p1)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m2 = batch_gradient_descent_l2(X_train,y2_tr,w,alpha,iters,lamb)
y_p2 = np.dot(X_test,w_m2.T)
y_p2 = set(y_p2)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m3 = batch_gradient_descent_l2(X_train,y3_tr,w,alpha,iters,lamb)
y_p3 = np.dot(X_test,w_m3.T)
y_p3 = set(y_p3)

w= np.zeros((X_train.shape[1])) ###weight initialization
w_m4 = batch_gradient_descent_l2(X_train,y4_tr,w,alpha,iters,lamb)
y_p4 = np.dot(X_test,w_m4.T)
y_p4 = set(y_p4)


In [25]:
cval = [0 for i in range(len(y_test))]
for i in range(len(y_test)):
    if (y_p1[i] == 1):
        cval[i] = 1.0
    if (y_p2[i] == 1):
        cval[i] = 2.0
    if (y_p3[i] == 1):
        cval[i] = 3.0
    if (y_p4[i] == 1):
        cval[i] = 4.0

GENERATING THE CONFUSION MATRIX

In [26]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, cval)

print(cm)

[[  6   0 153   2]
 [  3   0 153  11]
 [  4   0 170   5]
 [  5   0 161  10]]


FINDING INDIVIDUAL CLASS ACCURACY AND OVERALL ACCURACY

In [27]:
confmat = np.asarray(cm)
Acc = (confmat[0][0] + confmat[1][1] + confmat[2][2])/sum(sum(confmat))
Acc1 = confmat[0][0]/sum(confmat[0])
Acc2 = confmat[1][1]/sum(confmat[1])
Acc3 = confmat[2][2]/sum(confmat[2])
Acc4 = confmat[3][3]/sum(confmat[3])
print('Overall Accuracy : ' + str(Acc))
print('Accuracy of class 1 : ' + str(Acc1))
print('Accuracy of class 2 : ' + str(Acc2))
print('Accuracy of class 3 : ' + str(Acc3))
print('Accuracy of class 4 : ' + str(Acc4))

Overall Accuracy : 0.25768667642752563
Accuracy of class 1 : 0.037267080745341616
Accuracy of class 2 : 0.0
Accuracy of class 3 : 0.9497206703910615
Accuracy of class 4 : 0.056818181818181816
