Q4 ONE VS ONE

MOUNTING THE DRIVE

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


IMPORTING LIBRARIES

In [2]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import sklearn
np.random.seed(0)
import statistics

In [3]:
from sklearn.model_selection import train_test_split

DEFINING SIGMOID FUNCTION

In [4]:
def sigmoid(x):
  x = x.astype(float)
  z = np.exp(-x)
  sig = 1 / (1 + z)
  return sig

DEFINING SET FUNCTION

In [5]:
def set(y,k,j):
    for i in range(len(y)):
        if(y[i]>=0.5):
            y[i] = j
        if(y[i]<0.5):
            y[i] = k
    return y

DEFINING GRADIENT DESCENT FUNCTIONS

In [6]:
def batch_gradient_descent_l1(X,y,w,alpha,iters,lamb):
  
  cost_history = np.zeros(iters) # cost function for each iteration
  
  #initalize our cost history list to store the cost function on every iteration
  
  for i in range(iters):
    z = np.dot(X,w.T)
    hypothesis = sigmoid(z)
    w = w -  alpha * np.dot((hypothesis-y), X) - ((alpha*lamb/2)*np.sign(w))#weight updation
  
  return w

In [7]:
def batch_gradient_descent_l2(X,y,w,alpha,iters,lamb):
  
  cost_history = np.zeros(iters) # cost function for each iteration
  
  #initalize our cost history list to store the cost function on every iteration
  
  for i in range(iters):
    z = np.dot(X,w.T)
    hypothesis = sigmoid(z)
    w = w*(1-alpha*lamb) -  alpha * np.dot((hypothesis-y), X) #weight updation
  
  return w

In [8]:
def batch_gradient_descent(X,y,w,alpha,iters):
  
  cost_history = np.zeros(iters) # cost function for each iteration
  
  #initalize our cost history list to store the cost function on every iteration
  
  for i in range(iters):
    z = np.dot(X,w.T)
    hypothesis = sigmoid(z)
    w = w -  alpha * np.dot((hypothesis-y), X) #weight updation
  
  return w

LOADING THE DATA

In [9]:
data = pd.read_excel('/content/drive/MyDrive/nnfl data/data.xlsx',header=None)

In [10]:
datan=data.values
X=datan[:,0:datan.shape[1]-1]
y=datan[:,datan.shape[1]-1]
print(data.shape)

(3412, 61)


SPLITTING THE DATA INTO TRAINING, VALIDATION AND TESTING I.E. HOLDOUT VALIDATION

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, shuffle = True, random_state = 60)
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train,test_size=0.125, shuffle = True, random_state = 60)

NORMALISING THE DATA AND ADDING BIAS VECTOR

In [12]:
m=X_train.shape[0] 
n=X_test.shape[0]

qq = np.ones([n, 1])

xmin1 = np.min(X_test, axis = 0) 
xmax1 = np.max(X_test, axis = 0) 

X_test = (X_test- xmin1)/(xmax1-xmin1)

X_test = np.append(qq,X_test, axis=1)

In [13]:
xmin = np.min(X_train, axis = 0) 
xmax = np.max(X_train, axis = 0) 

X_train = (X_train- xmin)/(xmax-xmin)


In [14]:
pp = np.ones([m, 1])
X_train = np.append(pp,X_train, axis=1) #Column of ones 

print(X_train)

[[1.         0.4565523  0.70925588 ... 0.52205576 0.84817498 0.86645165]
 [1.         0.34247347 0.52862044 ... 0.20327721 0.81558568 0.71125864]
 [1.         0.59779369 0.24443946 ... 0.6853999  0.82794782 0.64855454]
 ...
 [1.         0.74693149 0.34984461 ... 0.21043456 0.84001243 0.84605655]
 [1.         0.23788388 0.25948086 ... 0.43523629 0.71647965 0.62122422]
 [1.         0.64374366 0.5491812  ... 0.5910701  0.8530399  0.66566898]]


In [15]:
x_tr=X_train
y_tr=y_train

In [16]:
print(y_tr)

[3. 2. 3. ... 4. 2. 3.]


MAKING MODELS FOR DIFFERENT OVE VS ONE CASES

In [17]:
y1_tr = [] # class 1 vs class 2
y2_tr = [] # class 1 vs class 3
y3_tr = [] # class 1 vs class 4
y4_tr = [] # class 2 vs class 3
y5_tr = [] # class 2 vs class 4
y6_tr = [] # class 3 vs class 4
x1_tr = [] 
x2_tr = []  
x3_tr = [] 
x4_tr = []
x5_tr = []
x6_tr = []


ADDING VALUES TO EACH ONE VS ONE CLASS LIST

In [18]:
for i in range(len(y_tr)):
    if(y_tr[i] != 3 and y_tr[i] != 4 ):
        y1_tr.append(y_tr[i])
        x1_tr.append(x_tr[i])
    if(y_tr[i] != 2 and y_tr[i] != 4):
        y2_tr.append(y_tr[i])
        x2_tr.append(x_tr[i])
    if(y_tr[i] != 2 and y_tr[i] != 3):
        y3_tr.append(y_tr[i])
        x3_tr.append(x_tr[i])
    if(y_tr[i] != 1 and y_tr[i] != 4):
        y4_tr.append(y_tr[i])
        x4_tr.append(x_tr[i])
    if(y_tr[i] != 1 and y_tr[i] != 3):
        y5_tr.append(y_tr[i])
        x5_tr.append(x_tr[i])
    if(y_tr[i] != 1 and y_tr[i] != 2):
        y6_tr.append(y_tr[i])
        x6_tr.append(x_tr[i])

In [19]:
x1_tr = np.asarray(x1_tr)
x2_tr = np.asarray(x2_tr)
x3_tr = np.asarray(x3_tr)
x4_tr = np.asarray(x4_tr)
x5_tr = np.asarray(x5_tr)
x6_tr = np.asarray(x6_tr)



DEFINING LOW AND HIGH FOR EACH CLASS CASE

In [20]:
for i in range(len(y1_tr)):
    if y1_tr[i] == 1:
        y1_tr[i] = 0
    else:
        y1_tr[i] = 1 

for i in range(len(y2_tr)):
    if y2_tr[i] == 1:
        y2_tr[i] = 0
    else:
        y2_tr[i] = 1 

for i in range(len(y3_tr)):
    if y3_tr[i] == 1:
        y3_tr[i] = 0
    else:
        y3_tr[i] = 1
for i in range(len(y4_tr)):
    if y4_tr[i] == 2:
        y4_tr[i] = 0
    else:
        y4_tr[i] = 1 
for i in range(len(y5_tr)):
    if y5_tr[i] == 2:
        y5_tr[i] = 0
    else:
        y5_tr[i] = 1 
for i in range(len(y6_tr)):
    if y6_tr[i] == 3:
        y6_tr[i] = 0
    else:
        y6_tr[i] = 1 

IMPLEMENTING BATCH GRADIENT DESCENT FOR MULTICLASS ONE VS ONE

In [21]:
alpha=0.008
iters=1000
w1= np.zeros((x1_tr.shape[1])) ###weight initialization
w_m1 = batch_gradient_descent(x1_tr,y1_tr,w1,alpha,iters)
y_p1 = np.dot(X_test,w_m1.T)
y_p1 = set(y_p1,1,2)


w2= np.zeros((x2_tr.shape[1])) ###weight initialization
w_m2 = batch_gradient_descent(x2_tr,y2_tr,w2,alpha,iters)
y_p2 = np.dot(X_test,w_m2.T)
y_p2 = set(y_p2,1,3)


w3= np.zeros((x3_tr.shape[1])) ###weight initialization
w_m3 = batch_gradient_descent(x3_tr,y3_tr,w3,alpha,iters)
y_p3 = np.dot(X_test,w_m3.T)
y_p3 = set(y_p3,1,4)


w4= np.zeros((x4_tr.shape[1])) ###weight initialization
w_m4 = batch_gradient_descent(x4_tr,y4_tr,w4,alpha,iters)
y_p4 = np.dot(X_test,w_m4.T)
y_p4 = set(y_p4,2,3)


w5= np.zeros((x5_tr.shape[1])) ###weight initialization
w_m5 = batch_gradient_descent(x5_tr,y5_tr,w5,alpha,iters)
y_p5 = np.dot(X_test,w_m5.T)
y_p5 = set(y_p5,2,4)


w6= np.zeros((x6_tr.shape[1])) ###weight initialization
w_m6 = batch_gradient_descent(x6_tr,y6_tr,w6,alpha,iters)
y_p6 = np.dot(X_test,w_m6.T)
y_p6 = set(y_p6,3,4)


DEFINING MODE FUNCTION

In [22]:
from collections import Counter
def my_mode(sample):
  return Counter(sample).most_common(1)[0][0]


CALCULATING MODE OF PREDICTED OUTPUT

In [23]:
from statistics import mode

cval = [0 for i in range(len(y_test))]

for i in range(len(y_test)):
  
  k=[y_p1[i],y_p2[i],y_p3[i],y_p4[i],y_p5[i],y_p6[i]]

  cval[i]=my_mode(k)


GENERATING CONFUSION MATRIX

In [24]:
for i in range(len(cval)):
    if (cval[i] == 0):
        cval[i] = 'None'

print(cval)
y_actual = pd.Series(y_test, name='Actual')
y_pred = pd.Series(cval, name='Predicted')
confmat = pd.crosstab(y_actual, y_pred)
print(confmat)

[3.0, 3.0, 3.0, 2.0, 4.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 2.0, 2.0, 4.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 4.0, 4.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 1.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 2.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 2.0, 2.0, 2.0, 3.0, 4.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 2.0, 4.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 2.0, 2.0,

FINDING ACCURACY

In [25]:

confmat = np.asarray(confmat)
Acc = (confmat[0][0] + confmat[1][1] + confmat[2][2])/sum(sum(confmat))
Acc1 = confmat[0][0]/sum(confmat[0])
Acc2 = confmat[1][1]/sum(confmat[1])
Acc3 = confmat[2][2]/sum(confmat[2])
Acc4 = confmat[3][3]/sum(confmat[3])
print('Overall Accuracy : ' + str(Acc))
print('Accuracy of class 1 : ' + str(Acc1))
print('Accuracy of class 2 : ' + str(Acc2))
print('Accuracy of class 3 : ' + str(Acc3))
print('Accuracy of class 4 : ' + str(Acc4))

Overall Accuracy : 0.22547584187408493
Accuracy of class 1 : 0.019867549668874173
Accuracy of class 2 : 0.1329479768786127
Accuracy of class 3 : 0.6736842105263158
Accuracy of class 4 : 0.047337278106508875


IMPLEMENTING BATCH GRADIENT DESCENT FOR MULTICLASS ONE VS ONE WITH L1 NORM

In [26]:
alpha=0.008
iters=1000
lamb=1
w1= np.zeros((x1_tr.shape[1])) ###weight initialization
w_m1 = batch_gradient_descent_l1(x1_tr,y1_tr,w1,alpha,iters,lamb)
y_p1 = np.dot(X_test,w_m1.T)
y_p1 = set(y_p1,1,2)


w2= np.zeros((x2_tr.shape[1])) ###weight initialization
w_m2 = batch_gradient_descent_l1(x2_tr,y2_tr,w2,alpha,iters,lamb)
y_p2 = np.dot(X_test,w_m2.T)
y_p2 = set(y_p2,1,3)


w3= np.zeros((x3_tr.shape[1])) ###weight initialization
w_m3 = batch_gradient_descent_l1(x3_tr,y3_tr,w3,alpha,iters,lamb)
y_p3 = np.dot(X_test,w_m3.T)
y_p3 = set(y_p3,1,4)


w4= np.zeros((x4_tr.shape[1])) ###weight initialization
w_m4 = batch_gradient_descent_l1(x4_tr,y4_tr,w4,alpha,iters,lamb)
y_p4 = np.dot(X_test,w_m4.T)
y_p4 = set(y_p4,2,3)


w5= np.zeros((x5_tr.shape[1])) ###weight initialization
w_m5 = batch_gradient_descent_l1(x5_tr,y5_tr,w5,alpha,iters,lamb)
y_p5 = np.dot(X_test,w_m5.T)
y_p5 = set(y_p5,2,4)


w6= np.zeros((x6_tr.shape[1])) ###weight initialization
w_m6 = batch_gradient_descent_l1(x6_tr,y6_tr,w6,alpha,iters,lamb)
y_p6 = np.dot(X_test,w_m6.T)
y_p6 = set(y_p6,3,4)

DEFINING MODE FUNCTION

In [27]:
from collections import Counter
def my_mode(sample):
  return Counter(sample).most_common(1)[0][0]

CALCULATING MODE OF PREDICTED OUTPUT

In [28]:
from statistics import mode

cval = [0 for i in range(len(y_test))]

for i in range(len(y_test)):
  k=[y_p1[i],y_p2[i],y_p3[i],y_p4[i],y_p5[i],y_p6[i]]

  cval[i]=my_mode(k)

GENERATING CONFUSION MATRIX

In [29]:
for i in range(len(cval)):
    if (cval[i] == 0):
        cval[i] = 'None'

print(cval)
y_actual = pd.Series(y_test, name='Actual')
y_pred = pd.Series(cval, name='Predicted')
confmat = pd.crosstab(y_actual, y_pred)
print(confmat)

[3.0, 3.0, 3.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 2.0, 2.0, 4.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 4.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 1.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 2.0, 2.0, 3.0, 3.0, 2.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 2.0, 4.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0,

FINDING ACCURACY

In [30]:

confmat = np.asarray(confmat)
Acc = (confmat[0][0] + confmat[1][1] + confmat[2][2])/sum(sum(confmat))
Acc1 = confmat[0][0]/sum(confmat[0])
Acc2 = confmat[1][1]/sum(confmat[1])
Acc3 = confmat[2][2]/sum(confmat[2])
Acc4 = confmat[3][3]/sum(confmat[3])
print('Overall Accuracy : ' + str(Acc))
print('Accuracy of class 1 : ' + str(Acc1))
print('Accuracy of class 2 : ' + str(Acc2))
print('Accuracy of class 3 : ' + str(Acc3))
print('Accuracy of class 4 : ' + str(Acc4))

Overall Accuracy : 0.23865300146412885
Accuracy of class 1 : 0.019867549668874173
Accuracy of class 2 : 0.10982658959537572
Accuracy of class 3 : 0.7421052631578947
Accuracy of class 4 : 0.029585798816568046


IMPLEMENTING BATCH GRADIENT DESCENT FOR MULTICLASS ONE VS ONE WITH L2 NORM

In [31]:
alpha=0.001
iters=1000
lamb=0.008
w1= np.zeros((x1_tr.shape[1])) ###weight initialization
w_m1 = batch_gradient_descent_l2(x1_tr,y1_tr,w1,alpha,iters,lamb)
y_p1 = np.dot(X_test,w_m1.T)
y_p1 = set(y_p1,1,2)


w2= np.zeros((x2_tr.shape[1])) ###weight initialization
w_m2 = batch_gradient_descent_l2(x2_tr,y2_tr,w2,alpha,iters,lamb)
y_p2 = np.dot(X_test,w_m2.T)
y_p2 = set(y_p2,1,3)


w3= np.zeros((x3_tr.shape[1])) ###weight initialization
w_m3 = batch_gradient_descent_l2(x3_tr,y3_tr,w3,alpha,iters,lamb)
y_p3 = np.dot(X_test,w_m3.T)
y_p3 = set(y_p3,1,4)


w4= np.zeros((x4_tr.shape[1])) ###weight initialization
w_m4 = batch_gradient_descent_l2(x4_tr,y4_tr,w4,alpha,iters,lamb)
y_p4 = np.dot(X_test,w_m4.T)
y_p4 = set(y_p4,2,3)


w5= np.zeros((x5_tr.shape[1])) ###weight initialization
w_m5 = batch_gradient_descent_l2(x5_tr,y5_tr,w5,alpha,iters,lamb)
y_p5 = np.dot(X_test,w_m5.T)
y_p5 = set(y_p5,2,4)


w6= np.zeros((x6_tr.shape[1])) ###weight initialization
w_m6 = batch_gradient_descent_l2(x6_tr,y6_tr,w6,alpha,iters,lamb)
y_p6 = np.dot(X_test,w_m6.T)
y_p6 = set(y_p6,3,4)

DEFINING MODE FUNCTION

In [32]:
from collections import Counter
def my_mode(sample):
  return Counter(sample).most_common(1)[0][0]

CALCULATING MODE OF PREDICTED OUTPUT

In [33]:
from statistics import mode

cval = [0 for i in range(len(y_test))]

for i in range(len(y_test)):
  k=[y_p1[i],y_p2[i],y_p3[i],y_p4[i],y_p5[i],y_p6[i]]

  cval[i]=my_mode(k)

GENERATING CONFUSION MATRIX

In [34]:
for i in range(len(cval)):
    if (cval[i] == 0):
        cval[i] = 'None'

print(cval)
y_actual = pd.Series(y_test, name='Actual')
y_pred = pd.Series(cval, name='Predicted')
confmat = pd.crosstab(y_actual, y_pred)
print(confmat)

[3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 2.0, 3.0, 2.0, 3.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 2.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0, 3.0, 2.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 4.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 2.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 2.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 2.0, 2.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 3.0, 2.0,

FINDING ACCURACY

In [35]:
confmat = np.asarray(confmat)
Acc = (confmat[0][0] + confmat[1][1] + confmat[2][2])/sum(sum(confmat))
Acc1 = confmat[0][0]/sum(confmat[0])
Acc2 = confmat[1][1]/sum(confmat[1])
Acc3 = confmat[2][2]/sum(confmat[2])
Acc4 = confmat[3][3]/sum(confmat[3])
print('Overall Accuracy : ' + str(Acc))
print('Accuracy of class 1 : ' + str(Acc1))
print('Accuracy of class 2 : ' + str(Acc2))
print('Accuracy of class 3 : ' + str(Acc3))
print('Accuracy of class 4 : ' + str(Acc4))

Overall Accuracy : 0.2547584187408492
Accuracy of class 1 : 0.013245033112582781
Accuracy of class 2 : 0.11560693641618497
Accuracy of class 3 : 0.8
Accuracy of class 4 : 0.011834319526627219
